-- Crop Sown Registry — sample lands and crop sown records (local / demo only).
--
-- The platform db-seed's load_sample_data.py is shaped for the reference
-- (farmer) registry, so LOAD_SAMPLE_DATA stays false for this variant and this
-- sample set is applied explicitly instead (see docker-compose.yml).
--
-- Farmers are identified, not stored: each crop sown record carries the
-- farmer's ids and name, and mirrors the Fayda FAN into link_foundational_id.
-- land_uuid is normally generated by the ORM; these rows spell it out so the
-- crop lines can reference a known value.

INSERT INTO "public"."g2p_register_lands" (
    "internal_record_id","functional_record_id","link_internal_record_id","link_foundational_id",
    "record_name","record_image_document_id","created_by","created_at","last_approved_at",
    "last_approved_by","search_text","record_status","record_status_reason",
    "land_uuid","land_id","is_land_registered","ownership_type","soil_fertility_type",
    "plot_category","land_area","unit","sub_kebele","latitude","longitude",
    "address_line_1","country_code"
) VALUES
('land0001','LND-000000000001',NULL,NULL,'OR/01/02/003/00001 2.5 HECTARE',NULL,'seeder','2026-04-01 00:00:00','2026-04-01 00:00:00','seeder','LND-000000000001 11111111-1111-4111-8111-111111111111 OR/01/02/003/00001 OWNER MEDIUM ANNUAL_CROP 2.5 HECTARE Gote 3','ACTIVE',NULL,'11111111-1111-4111-8111-111111111111','OR/01/02/003/00001',TRUE,'OWNER','MEDIUM','ANNUAL_CROP',2.5,'HECTARE','Gote 3','9.0310','38.7420','Kebele 01','ETH'),
('land0002','LND-000000000002',NULL,NULL,'OR/01/02/003/00002 1.0 HECTARE',NULL,'seeder','2026-04-01 00:00:00','2026-04-01 00:00:00','seeder','LND-000000000002 22222222-2222-4222-8222-222222222222 OR/01/02/003/00002 TENANT LOW ANNUAL_CROP 1.0 HECTARE Gote 3','ACTIVE',NULL,'22222222-2222-4222-8222-222222222222','OR/01/02/003/00002',TRUE,'TENANT','LOW','ANNUAL_CROP',1.0,'HECTARE','Gote 3','9.0325','38.7455','Kebele 01','ETH'),
('land0003','LND-000000000003',NULL,NULL,'AM/04/01/007/00011 3.75 HECTARE',NULL,'seeder','2026-04-01 00:00:00','2026-04-01 00:00:00','seeder','LND-000000000003 33333333-3333-4333-8333-333333333333 AM/04/01/007/00011 OWNER HIGH ANNUAL_CROP 3.75 HECTARE Gote 1','ACTIVE',NULL,'33333333-3333-4333-8333-333333333333','AM/04/01/007/00011',TRUE,'OWNER','HIGH','ANNUAL_CROP',3.75,'HECTARE','Gote 1','8.5415','39.2712','Kebele 04','ETH')
ON CONFLICT ("internal_record_id") DO NOTHING;

INSERT INTO "public"."g2p_register_crop_sowns" (
    "internal_record_id","functional_record_id","link_internal_record_id","link_foundational_id",
    "record_name","record_image_document_id","created_by","created_at","last_approved_at",
    "last_approved_by","search_text","record_status","record_status_reason",
    "farmer_uuid","farmer_id","fayda_fan_id","farmer_name","land_uuid","status",
    "production_year","lifecycle_stage","surveyor_name","surveyor_mobile_number",
    "supervisor_name","supervisor_mobile_number","latitude","longitude",
    "address_line_1","address_line_2","country_code"
) VALUES
('cs0001','CS-000000000001',NULL,'1234567890','Abebe Kebede 2026',NULL,'seeder','2026-04-01 00:00:00','2026-04-01 00:00:00','seeder','CS-000000000001 Abebe Kebede FN-0001 1234567890 OR/01/02/003/00001 APPROVED 2026 SOWING','ACTIVE',NULL,'a0000000-0000-4000-8000-000000000001','FN-0001','1234567890','Abebe Kebede','11111111-1111-4111-8111-111111111111','APPROVED','2026','SOWING','Chala Tesfaye','+251911000001','Muluken Assefa','+251911000002','9.0300','38.7400','Kebele 01','Gote 3','ETH'),
('cs0002','CS-000000000002',NULL,'9876543210','Almaz Tadesse 2026',NULL,'seeder','2026-04-01 00:00:00','2026-04-01 00:00:00','seeder','CS-000000000002 Almaz Tadesse FN-0002 9876543210 AM/04/01/007/00011 APPROVED 2026 HARVESTING','ACTIVE',NULL,'a0000000-0000-4000-8000-000000000002','FN-0002','9876543210','Almaz Tadesse','33333333-3333-4333-8333-333333333333','APPROVED','2026','HARVESTING','Chala Tesfaye','+251911000001','Muluken Assefa','+251911000002','8.5400','39.2700','Kebele 04','Gote 1','ETH')
ON CONFLICT ("internal_record_id") DO NOTHING;
